### ISSUE TITLE
Font not recognized as monospaced on Mac OS 12.4

### ISSUE THREAD

**Issue by maxwellpalmer** [0xType/0xProto#1]
In MacOS 12.4, the font isn't recognized as a monospaced font. Applications that only allow monospaced fonts, such as RStudio, don't show the font as an option.

**Comment by masaakim** [comment]
@maxwellpalmer  Thank you for using 0xProto!

I've just created https://github.com/0xType/0xProto/pull/2 to fix this problem. Could you check again with the following font files?

[0xProto_for_maxwellpalmer.zip](https://github.com/0xType/0xProto/files/11619858/0xProto_for_maxwellpalmer.zip)

**Comment by maxwellpalmer** [comment]
That worked for me. Thank you!
