### ISSUE TITLE
Font is not listed in cmd / mobaxterm

### ISSUE THREAD

**Issue by anilkumar150886** [0xType/0xProto#10]
0xProto is not visible in windows command prompt !! I have installed from .ttf file, but still not able to see it.!!
Not sure in mac though..!!

![image](https://github.com/0xType/0xProto/assets/16396710/cb9b3486-140c-4ccb-bc25-f3b957d92123)

**Comment by masaakim** [comment]
@anilkumar150886 Thank you for using 0xProto.

I recently tested 0xProto on the Windows 11 command prompt and it worked perfectly.

I have a couple of questions for you:
1. Which version of Windows are you currently using?
2. Is it possible to use 0xProto in applications other than the command prompt? (Were you able to successfully install the fonts?)"

**Comment by anilkumar150886** [comment]
I'm using windows 10.. I'm able to use the font in VSCode, Visual Studio, Notepad++.. But not in Cmd..

In MobaXterm, i'm able to see the fonts, but the spacing is too wide.. 

![image](https://github.com/0xType/0xProto/assets/16396710/1e1629b0-162c-4056-ad90-d1a8a110e4fc)

I think cmd / terminals / consoles supports monospace characters. .!!

**Comment by masaakim** [comment]
@anilkumar150886  Hmm... What version of 0xProto are you using? If you are using v1.000, it may not be recognized as a monospaced font. I fixed that bug in https://github.com/0xType/0xProto/pull/2 and it should work in v1.001 or later.

If you are already using v1.001 or later, if you have time, please try .otf files instead of .ttf.

**Comment by anilkumar150886** [comment]
Tried both *.ttf and *.otf.. with no Luck!!  

![image](https://github.com/0xType/0xProto/assets/16396710/cc4207cb-3325-4fab-84c2-3b34f88846b9)

**Comment by masaakim** [comment]
Thanks for checking!
I will keep this in mind. Perhaps there are other flags, etc. to indicate that it is a monospace font.

**Comment by anilkumar150886** [comment]
Thank you.. 
I see, your font is going to be selected as one of the favorite coding languages, for sure..
It just needs more improvisation, if you starting addressing issues and introduce more font family weights..!!

**Comment by masaakim** [comment]
Thank you!
I have no plans to add font family weights. Please see https://github.com/0xType/0xProto/issues/12 .
Well, please wait a bit as I will do my own research on this issue you have discovered.

**Comment by masaakim** [comment]
@anilkumar150886 Hi. The following zip file contains font files with changes that attempt to resolve this issue.
If you have time, could you install this font file and check again?

[0xProto_1.101_beta.zip](https://github.com/0xType/0xProto/files/12503771/0xProto_1.101_beta.zip)

**Comment by anilkumar150886** [comment]
@masaakim Thanks!!. I was able to test and now the font is recognized in cmd..  it looks good.. **but in mobaxterm, the fonts are very wide..**

![image](https://github.com/0xType/0xProto/assets/16396710/e8e72057-db46-4360-bd85-2aa8f7d28680)

Mobaxterm needs fixing on width spacing..!!

![image](https://github.com/0xType/0xProto/assets/16396710/29f4f0e1-e011-45b3-8c96-68819d9f862b)

**Comment by masaakim** [comment]
@anilkumar150886 Thanks for checking! I'm glad you can now reference fonts in Command Prompt in Windows 10.
(FYI: https://github.com/0xType/0xProto/pull/13 is the PR to solve this problem. )

**Comment by masaakim** [comment]
> Mobaxterm needs fixing on width spacing..!!

Thanks for the feedback. I will try to fix this issue next.
I don't want to deal with multiple issues on one issue, so I created a new separate issue. https://github.com/0xType/0xProto/issues/14

**Comment by anilkumar150886** [comment]
So, One real feedback which you might very often from everyone , is on different "Weights". 
You might have to rethink on your decision and give more options to users as per their choice...  Cheers,..!!
