### ISSUE TITLE
[Question] What font size and line height would you recommend? 

### ISSUE THREAD

**Issue by TiLopes** [0xType/0xProto#11]
Started using it in VSCode and i'm trying to get used to having a thicker "weight" by default. To improve the experience I would to know what font size and line height would provide better legibility and a better experience overall.

**Comment by masaakim** [comment]
@TiLopes Thank you for using 0xProto! 

There isn't a one-size-fits-all solution to determining the optimal font size and line height for enhanced legibility and experience. These factors are influenced by the display's resolution and color range, the user's eyesight, and their aesthetic preferences. 

For what it's worth, I code in VSCode using 0xProto. While I can't be certain if this will be helpful to you, here's my current setup.

```
{
  ...
  "editor.fontSize": 13,
  "editor.fontFamily": "'0xProto'",
  "editor.fontLigatures": true,
  ...
}
```

For line height, I use the default value. Apparently, if 0 is used, automatically compute it from the font size.

<img width="602" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/e6b60082-823c-4c34-81b5-c74fec56664c">
