### ISSUE TITLE
Make the tilde more pronounced

### ISSUE THREAD

**Issue by ktekinay** [0xType/0xProto#16]
The tilde (`~`) is somewhat flat and, especially at smaller sizes, hard to distinguish from the hyphen (`-`). Please add more curvature to it.

By way of illustration, here is the same line in both 0xProto and JetBrains Mono at 16 pt.

<img width="331" alt="Screenshot 2023-09-14 at 11 32 37 AM" src="https://github.com/0xType/0xProto/assets/2513909/d2ee4907-4926-4af2-9a25-43facb92fa86">

**Comment by masaakim** [comment]
@ktekinay Thanks again! Actually, the "~" legibility was my concern as well, and I was planning to include it in the next release.👍

**Comment by masaakim** [comment]
The shape of `~` will be updated in the next release of 0xProto! https://github.com/0xType/0xProto/pull/18

<img width="593" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/dc2cc450-4ec0-4c0a-96e2-7a63921876b9">


<img width="1080" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/a25e29c5-34bf-4089-a69d-43da7903a090">

**Comment by masaakim** [comment]
I've just released v1.200! https://github.com/0xType/0xProto/releases/tag/1.200

**Comment by ktekinay** [comment]
That looks great, thanks!
