### ISSUE TITLE
Issue with the continuous asterisk

### ISSUE THREAD

**Issue by sonulohani** [0xType/0xProto#19]
In c++ docs, I see this pattern which looks very horrible,

![image](https://github.com/0xType/0xProto/assets/2958681/15fd0734-2954-49ed-96b6-3520853b7d03)

For three asterisk, its fine, but not for more than 3. Seems like a ligature problem. Please fix it.

**Comment by masaakim** [comment]
@sonulohani Thanks for pointing that out. I'll look into it and make the necessary corrections.

**Comment by masaakim** [comment]
Finally! I was able to fix this issue in my local build.

<img width="788" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/aeab1ea3-14a7-4062-a197-a425111b7a66">

However, to release this, I'll need to adjust the feature settings for all ligatures, not just the three asterisks. So, I appreciate your patience— it'll be just a bit longer.

**Comment by sonulohani** [comment]
Thanks for fixing it, eagerly waiting for this release. Take your time. :-)

**Comment by masaakim** [comment]
@sonulohani I've just released [v1.201](https://github.com/0xType/0xProto/releases/tag/1.201) which addresses this issue. Thanks!
