### ISSUE TITLE
Italic Font Family

### ISSUE THREAD

**Issue by msherifs** [0xType/0xProto#20]
does italics support is on the road map ?

**Comment by masaakim** [comment]
@msherifs Thank you for using 0xProto!

I'm considering adding a script font to 0xProto, not just an italic version.

Text editors like VSCode can utilize different font families for specific reserved words in programming languages. [Operator Mono](https://www.typography.com/blog/introducing-operator) is a notable example of this.

I believe incorporating script fonts into 0xProto will enhance character identification when coding.

However, introducing a new font family is as time-consuming as creating a new font from scratch. While I can't provide an exact timeline, I'm hopeful to include this feature in the next major release.

**Comment by sonulohani** [comment]
Waiting for this to release

**Comment by masaakim** [comment]
Finally got the update done – now supporting 344 languages!
https://github.com/0xType/0xProto/releases/tag/1.600

Time to dive into the next issue on the list 🔥

**Comment by arjpar** [comment]
@masaakim the latest update doesnt have an italic font file; are italics planned for the next release? it would also be nice to eventually add bold and bold italic font styles but that can come once other more immediate design goals/requirements are achieved/met.

**Comment by masaakim** [comment]
@arjpar Yes, just like mentioned in https://github.com/0xType/0xProto/issues/20#issuecomment-1727205411 , adding italics is gonna take a bit. We're aiming to include it in the next big update.

and FYI: I currently have no plans to add some weights. see also https://github.com/0xType/0xProto/issues/51#issuecomment-1871041738

**Comment by valpackett** [comment]
I love the way [Victor Mono](https://rubjo.github.io/victor-mono/)'s italic/cursive looks, would be excellent if yours would be a similar type of look :3

**Comment by liliantdn** [comment]
I absolutely love the way the italics look in [IBM Plex Mono](https://github.com/IBM/plex), could be a good source of inspiration as well if needed :)

![image](https://github.com/0xType/0xProto/assets/90719210/7c3a1023-17fd-4dcc-852a-5741b5dc0a17)

**Comment by masaakim** [comment]
The italic version of 0xProto has to resemble the original 0xProto style, and we're actively working to ensure it does, with a special focus on making it legibile. I'm also carefully considering other fonts like Victor Mono and IBM Plex Mono as references.

I'll be able to share a draft with you shortly. While I can't set a concrete release date just yet, I'm targeting a release in May.

**Comment by masaakim** [comment]
Hi there, this is still being adjusted, but this is what it currently looks like 😉

![image](https://github.com/0xType/0xProto/assets/1401513/917df3f7-714a-4f0a-a5d6-7632d008e38b)

![image](https://github.com/0xType/0xProto/assets/1401513/7d8fe33e-2451-4852-b9dc-4a57c961f6ac)

**Comment by codesjedi** [comment]
+1 for this feature, I'd love to use it in code comments

**Comment by masaakim** [comment]
I've finally finished creating all the glyphs for 0xProto Italic!

v2.000, which includes 0xProto Italic, will be released later this month. I'll make some final tweaks before then and address a few concerns I have with some existing glyphs. It's beta version yet, but 0xProto Italic is available now, and I've attached the font files. If you have any feedback, please let me know.

[0xProto-Italic-beta.zip](https://github.com/0xType/0xProto/files/15023956/0xProto-Italic-beta.zip)

**Comment by sonulohani** [comment]
The font is looking great. Some of the characters are not at the same level, for example 'r' and 's'

![image](https://github.com/0xType/0xProto/assets/2958681/7a5a5dfb-3371-48ba-8346-2e84f6f39633)

**Comment by sonulohani** [comment]
This is Monolisa font

![image](https://github.com/0xType/0xProto/assets/2958681/9f9b2e9b-99c2-4118-85b9-a5bb078093fb)
![image](https://github.com/0xType/0xProto/assets/2958681/ed96d8b9-7584-4ea9-a276-3632312062c6)

**Comment by masaakim** [comment]
@sonulohani Thanks for the quick feedback!

> Some of the characters are not at the same level

What does level refer to? the hight of the glyph?
For the `s` it was intentionally made higher than the x-height height to make the counter portion wider and increase legibility. What do you think?

<img width="2201" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/758ca8f8-6feb-4550-9061-44fdc2c1d65b">

**Comment by masaakim** [comment]
Fine-tuned. It is true that the head of the `s` may have been a little too large.

<img width="2090" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/442257f7-e2a7-4795-a087-7085ff9d4187">

I've been brainstorming a ton of completely new glyph designs for letters like 's' and 'r', and honestly, I'm starting to lose track of them all. So, getting feedback like this is really helpful.

<img width="1460" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/5bfb21c2-b26f-4c2b-a908-8fb6d0a20d51">

**Comment by sonulohani** [comment]
No problem. It's our duty to provide feedback for the product we are using which is thankfully free.

**Comment by sonulohani** [comment]
For your reference,

![image](https://github.com/0xType/0xProto/assets/2958681/0d03e7fb-05fe-4391-bd27-284b29e5176f)

This screenshot may be helpful for you. 

Other characters are looking awesome and has equal height. The character 'r' and 's' are the one which goes slightly higher in the alignment which I think may be addressed by now. 's' is looking like its about to fly :-).

**Comment by masaakim** [comment]
I also have a Plus license for Monolisa so I can compare on my own laptop 👍

**Comment by my4ng** [comment]
Awesome font, thank you! Is it possible to have a non cursive variant too? Cascodia Code uses Stylistic Set “ss01” to change between cursive and non cursive variants.

**Comment by masaakim** [comment]
@my4ng My pleasure :)

> Is it possible to have a non cursive variant too? Cascodia Code uses Stylistic Set “ss01” to change between cursive and non cursive variants.

With the changes in this PR ( https://github.com/0xType/0xProto/pull/66 ), that's not possible. But I agree that adding stylistic sets for non-cursive variants would be beneficial.
Preparations for the v2.000 release are almost complete and we intend to release it this month. So I will add these stylistic sets after v2.000 is released. I've created a new issue! https://github.com/0xType/0xProto/issues/71

**Comment by masaakim** [comment]
Exciting news—I've just released [v2.000](https://github.com/0xType/0xProto/releases/tag/2.000) of 0xProto, now with 0xProto Italic included! This marks the largest update since the original release nearly a year ago.
The introduction of 0xProto Italic is a direct result of the feedback many of you shared. I'm incredibly grateful for your support and input. Thank you all so much!

**Comment by arjpar** [comment]
@masaakim congrats on v2.000! I submitted a [PR](https://github.com/Homebrew/homebrew-cask-fonts/pull/9317) to homebrew-cask-fonts to update the font to v2.000 for all homebrew users.

**Comment by masaakim** [comment]
Thanks @arjpar , nice work!

**Comment by my4ng** [comment]
@masaakim the new italic looks and feels great! I have also submitted an update [PR](https://github.com/ryanoasis/nerd-fonts/pull/1623) to nerd fonts.

**Comment by WindSoilder** [comment]
@masaakim Thank you for the new italic font!  I love it very much

**Comment by adrian5** [comment]
Outstanding work @masaakim, I only just discovered this font today!
