### ISSUE TITLE
Not recognized in the cmd.exe on Windows 10

### ISSUE THREAD

**Issue by masaakim** [0xType/0xProto#21]
## What 

https://github.com/0xType/0xProto/issues/15#issuecomment-1727352909

> This time, on v1.2 version, the font was listing in the cmd, but it was not getting recognized as font. i.e, Whenever i selected the 0xProto, it was defaulted back to courier new.

> With v1.101, it's fine, i.e, when i select the 0xProto, the font is recognized.

Something is wrong with the changes in v1.200.

**Comment by masaakim** [comment]
I verified on my Windows 11 machine and 0xProto v1.200 appears in the list in the cmd and I was able to use it.

@anilkumar150886 Hi, Is your environment Windows 10?

**Comment by anilkumar150886** [comment]
yeah.. my env is windows 10..
