### ISSUE TITLE
Accented letters do not match the rest of the font.

### ISSUE THREAD

**Issue by TiLopes** [0xType/0xProto#22]
Accented letters do match the rest of the characters of the font. Here are some examples:
![image](https://github.com/0xType/0xProto/assets/106965010/92794516-a897-46a1-bf2d-35098279cec2)
When used in a word:
![image](https://github.com/0xType/0xProto/assets/106965010/d2f68819-a4dd-4972-bfbd-605dc54bdb38)

**Comment by masaakim** [comment]
@TiLopes Thank you for using 0xProto!

Yes, as of now, 0xProto doesn't include glyphs for accented letters. So, it's not a bug but rather a design choice.

While I'm not opposed to supporting accented letters, it's a lower priority for the following reasons:

- 0xProto is primarily a font for programming.
- Accented letters aren't typically used in source code, apart from comments.
- Comments can also be composed in English.

**Comment by ktekinay** [comment]
FYI, I started an Issue with Nerd Fonts to include 0xProto.

https://github.com/ryanoasis/nerd-fonts/issues/1379

**Comment by ktekinay** [comment]
A couple of points to consider here:

- Other coding fonts include accented characters, and 0xProto is "competing" with them.
- Accented characters are used in variable names by non-English coders, and may be used in string constants by anyone.

**Comment by masaakim** [comment]
Yeah, that's true, but That does not make accented letters a higher priority. I believe the [script font family](https://github.com/0xType/0xProto/issues/20) has a higher priority.

I am not saying that accented letters will not be supported. So I am leaving this issue open as well. It is just a matter of priority.

**Comment by masaakim** [comment]
I've decided to elevate the priority of this issue. 

I've come to realize that programmers whose native language is a non-English Latin-based one (e.g., French, Spanish, etc.) incorporate their language into their source code more frequently than I initially thought. 
My misjudgment stemmed from the fact that, being a native Japanese speaker, we rarely use Japanese in source code, except in comments.

**Comment by masaakim** [comment]
@TiLopes @ktekinay
Hi there, I've just released [v1.400](https://github.com/0xType/0xProto/releases/tag/1.400) to support accented letters.
Now, 0xProto supports 210 languages! (according to [Hyperglot](https://hyperglot.rosettatype.com/))
