### ISSUE TITLE
Display Issue in VS Code Terminal

### ISSUE THREAD

**Issue by Pon57** [0xType/0xProto#25]
I've been experiencing a display issue when using 0xProto in the VS Code terminal. The characters appear broken or distorted, making it difficult to read the text.

<img width="439" alt="スクリーンショット 2023-09-30 17 47 57" src="https://github.com/0xType/0xProto/assets/15137243/49c21d44-e849-4731-9739-b19e238843c2">

In this screenshot, the following string is displayed:
```bash
bash-3.2$ echo "hello"
hello
bash-3.2$ 
```

## Steps to Reproduce:

1. Install 0xProto(.otf) and set it as the default font for the VS Code terminal. `"terminal.integrated.fontFamily": "0xProto"`
2. Observe the broken or distorted characters.

## Additional Information

VS Code Version: 1.82.2 (Universal)
OS: macOS Sonoma 14.0 (I've also observed this issue on Ventura)
0xProto Version: 1.201
VS Code terminal font size: `"terminal.integrated.fontSize": 12`

I love using 0xProto and would greatly appreciate any assistance in resolving this issue. Thank you for your time and consideration.

**Comment by masaakim** [comment]
@Pon57  Thanks for the detailed feedback and information.

I'm using 0xProto without any issues on the same VS Code, OS, and 0xProto version as yours.

Based on the screenshot you provided, it seems like the terminal is displaying a glyph from a font other than 0xProto. It might be defaulting to another monospaced font installed on your system or one that comes pre-installed with your OS.

Considering the information you've shared, there are two potential culprits:

1. 0xProto might not be correctly installed.
2. There could be some misconfigurations in your VS Code settings.

If you can use 0xProto seamlessly in other applications, like iTerm2, then it likely isn't the first option.

**Comment by Pon57** [comment]
@masaakim Thank you for your reply!

I found a difference between the Terminal settings and the Editor settings. It seems to be applied correctly by setting it to "0xProto". I had removed the double quotation marks around 0xProto, so it seems I wasn't able to configure it properly.

✅ `"terminal.integrated.fontFamily": "\"0xProto\""`
🙅 `"terminal.integrated.fontFamily": "0xProto"`

<img width="495" alt="スクリーンショット 2023-10-01 1 31 58" src="https://github.com/0xType/0xProto/assets/15137243/af0ec613-0cb2-4b61-9582-80f829519341">

I apologize for the inconvenience caused by my configuration mistake. Thank you for your assistance!

Since the issue has been resolved, I will close this issue.

**Comment by masaakim** [comment]
Great!

FYI: 
Per the [OpenType specification](https://learn.microsoft.com/en-us/typography/opentype/spec/name), there aren't any restrictions on font names, so '0xProto' is perfectly valid. However, in applications like VS Code, where you enter the font name into a text field, it requires the name to be enclosed in quotation marks. This isn't typical for other fonts. Given that the font name '0xProto' starts with a number, it isn't the most user-friendly experience. As a result, I'm considering renaming the font, if necessary. (I like the name '0xProto', though of course I don't want to rename it.)
