### ISSUE TITLE
Should I rename 0xProto?

### ISSUE THREAD

**Issue by masaakim** [0xType/0xProto#27]
Per the [OpenType specification](https://learn.microsoft.com/en-us/typography/opentype/spec/name), there aren't any restrictions on font names, so '0xProto' is perfectly valid. However, in applications like VS Code, where you enter the font name into a text field, it requires the name to be enclosed in quotation marks. This isn't typical for other fonts. Given that the font name '0xProto' starts with a number, it isn't the most user-friendly experience.

As a result, I'm considering renaming the font, if necessary. (I'm really fond of the name '0xProto' and, honestly, I'd be reluctant to change it for sentimental reasons.)

**Comment by VoilaNeighbor** [comment]
I think the name is fine. Also, it comes the first when you browse the font list :p

**Comment by ktekinay** [comment]
I'd rename it, but then, I'm not attached to the name. 😃 

If it would let it work in Mail.app, I'd definitely rename it.

But this is not a deal-breaker either way.

**Comment by masaakim** [comment]
@ktekinay See https://github.com/0xType/0xProto/issues/15#issuecomment-1741927201 and https://github.com/0xType/0xProto/issues/26

> Even with the name changed to zxProto, the font wasn't available on Mail.app. Hence, I've determined that the issue isn't tied to the name '0xProto'.

> I consider this issue to be of low priority since 0xProto is a programming font.

**Comment by Finii** [comment]
When generating the font named `3270` (from `IBM 3270`) I annotated the naming with this comment
```
    SIL_TABLE = [   
        ...
        ( '(t)erminus',                 r'\1erminess' ),
        # Noone cares that font names starting with a digit are forbidden:
        ( 'IBM 3270',                   r'3270'), # for historical reasons and 'IBM' is a TM or something
        ...
```

I have no recollection where I got that statement from and a quick search turned up empty. Maybe it is an Adobe/Postscript thing (but I searched there also).

Anyhow, the font `3270` is out since a decade and I have never heard any complains about the name.

**Comment by Finii** [comment]
> I have no recollection where I got that statement from

https://github.com/fontforge/fontforge/blob/4f4907d9541857b135bd0b361099e778325b4e28/fontforgeexe/fontinfo.c#L2624-L2626

Could not find out where George got that from, has been in the code since the initial commit.

(I still believe you can ignore it)

**Comment by masaakim** [comment]
@Finii Thanks for the detailed information!

**Comment by masaakim** [comment]
After much research and consideration over the past month, I've decided against changing the name 0xProto.

> in applications like VS Code, where you enter the font name into a text field, it requires the name to be enclosed in quotation marks.

As far as I know now, this is the only drawback caused by the name '0xProto'. So, I decided to prioritize identity over a little inconvenience.
