### ISSUE TITLE
Uneven character spacing

### ISSUE THREAD

**Issue by VoilaNeighbor** [0xType/0xProto#28]
I just found this font yesterday, and got quite in love with it. It's lively and lovely with the curly strokes and very legible with the terminals.

However, I find that the letter spacing could be a little uneven. For example, the `c` and `o` are too apart, while the double `m`'s are too close.

![image](https://github.com/0xType/0xProto/assets/92033182/f63429e2-bf10-4d4e-80c6-0913265fff43)

What do you think?

**Comment by masaakim** [comment]
@VoilaNeighbor Thank you for using 0xProto!

Absolutely. If 0xProto were a proportional font, the `m` would naturally be wider, and there'd be kerning between characters like `c` and `o`.
But given that 0xProto is monospaced, each character must fit within the same width box.

This means wide glyphs like `m` and `w` are somewhat constricted to fit that fixed-width. If we sized the box based on a naturally wider character like `m`, then narrower characters such as `i` and `l` would end up with too much space around them.
So, that approach just wouldn't be feasible, if that makes sense.

As an example, samples of other programming fonts are included below:

#### Fira Code

<img width="487" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/3bf0a6b8-1136-4a13-a0bb-e5b72dc7f1bf">

#### JetBrains Mono

<img width="484" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/ebab9a22-14b5-410f-8d82-caf898d3124e">

#### Monaco

<img width="479" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/3d65a73d-7134-4632-a3e7-60c9d9539736">

**Comment by VoilaNeighbor** [comment]
Hey thanks for your detailed explanations bro. I'm now a big fan of your typeface. :)

Thanks for sharing this beautiful font with the world.
