### ISSUE TITLE
Make the capital "L" stand out more

### ISSUE THREAD

**Issue by ktekinay** [0xType/0xProto#30]
Frankly, this might just be a "me" issue, but today I ran into a compiler error that was not immediately obvious. The problem was that I had typed "CLaim" instead of "Claim", and the difference between the upper- and lowercase "L" took some squinting.

Any way to make the L's more distinct?

(And "no, make your font size bigger, you half-wit!" is a perfectly acceptable answer here.)

**Comment by masaakim** [comment]
Hi, @ktekinay 

I personally typed it out and reviewed it, and I felt the distinction was clear enough, especially when compared to other similar letters.

<img width="923" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/76493864-ae07-4bc1-b559-37be54eaa07b">

In terms of making characters more distinguishable, differentiating between uppercase and lowercase letters, like 'S' and 's' or 'X' and 'x', would be a higher priority in my view.
