### ISSUE TITLE
Minor notes on Copyright / Vendor ID

### ISSUE THREAD

**Issue by Finii** [0xType/0xProto#31]
Just some nerdy technical comments (sorry, but being nerdy is my business):

You seem to use `NONE` as VendorID.
This also shows up in the UniqueID: `1.300;NONE;0xProto`
That might not be the best solution.

The copyright field in the font file is empty, conflicting the LICENSE file:

![image](https://github.com/0xType/0xProto/assets/16012374/696617c9-a908-48d7-a4f8-29f83beebbea)

And finally:
```
The glyph named uni2545 is mapped to U+2534.
  But its name indicates it should be mapped to U+2545.
```
The glyph is correct but the name is in error.
Not sure why, but U+2545 is named `uni2545.001`

_Edit 1:_

https://github.com/0xType/0xProto/blob/38a70987fd29322a1e09114323e756f5ee3cfbb1/0xProto-Regular.ufo/lib.plist#L461-L464

_Edit 2:_

The names of 2534 obviously got ... mixed up
https://github.com/0xType/0xProto/blob/main/0xProto-Regular.ufo/glyphs/boxL_eftD_ownH_eavyA_ndR_ightU_pL_ight.glif

All these issues are not relevant to the ordinary user.

**Comment by masaakim** [comment]
@Finii Good catch! I'll include it in the next release and in future releases as well.

> being nerdy is my business

I think your work is absolutely excellent ;)
