### ISSUE TITLE
y is somewhat narrow

### ISSUE THREAD

**Issue by sonulohani** [0xType/0xProto#32]
it seems that y letter is somewhat compressed, same goes with d.
![image](https://github.com/0xType/0xProto/assets/2958681/ce2144e6-38f9-440b-9db9-fb12092e64da)
Is it possible to fix this? thanks

**Comment by masaakim** [comment]
I have to disagree. Whether or not it looks good depends on the characters before and after. Also, monospace fonts don't have kerning information.
