### ISSUE TITLE
[Feature Request] Turkish characters support

### ISSUE THREAD

**Issue by dincertekin** [0xType/0xProto#37]
Hello, I really love this font. When I programming its my always favorite. And I saw you added some supports for languages. Can you add Turkish characters support?
We've characters like: ı, ğ, ü, ş, İ, ö, ç

**Comment by masaakim** [comment]
@dincertekin Thanks for using 0xProto!

> Can you add Turkish characters support?

Absolutely! I'll work on adding Turkish support as soon as I can.
However, I ask for your patience until we resolve PR https://github.com/0xType/0xProto/pull/36 . The inclusion of this new glyph will impact the changes proposed in that PR.

**Comment by masaakim** [comment]
Hi @dincertekin 
I've just released [v1.402](https://github.com/0xType/0xProto/releases/tag/1.402) to support Turkish characters!
