### ISSUE TITLE
Dotted zero

### ISSUE THREAD

**Issue by brzzdev** [0xType/0xProto#4]
A dotted zero variant would be amazing!

**Comment by masaakim** [comment]
@brzzdev Thank you for using!

Creating a variant is easy, but let me give you a few thoughts.
0xProto is my first experimental typeface project, and as the README says, it is opinionated. I have plans to create a generic programming font that is not opinionated. I think that variants such as the dotted zero you suggested might only need to be supported in that generic programming font.

**Comment by brzzdev** [comment]
Yeah, that's fair enough
