### ISSUE TITLE
Support more characters in more languages

### ISSUE THREAD

**Issue by masaakim** [0xType/0xProto#45]
Rather than adding glyphs for a new language on a request basis, as seen in issues #44 and #37, I'll review the languages supported by larger companies like [Intel One Mono](https://github.com/intel/intel-one-mono) and [JetBrains Mono](https://github.com/JetBrains/JetBrainsMon) and incorporate the necessary glyphs accordingly.

**Comment by masaakim** [comment]
I've finalized a policy regarding this matter.

In summary, 0xProto will only support the Latin script. 
This decision is based on the fact that both GitHub's [monaspace](https://github.com/githubnext/monaspace) and Intel One Mono support only the Latin script. 

While it's ideal to support a wide range of languages, and I'm not opposed to including the Cyrillic alphabet, as a native Japanese speaker, I understand the challenges in creating a comprehensive glyph set for Japanese. 
Increasing the number of glyphs in a font also escalates the management cost. 
Since I work on fonts in my personal and non-professional time, my resources are limited, necessitating a clear boundary. 

0xProto will support the Latin script, aiming for language coverage similar to GitHub's monaspace, which supports 275 languages, or Intel One Mono's 311.

Thanks!

**Comment by AndydeCleyre** [comment]
Firstly, thank you for this beautiful font, with a great and clear goal!

Two obscure characters that I use, that do seem to be part of the Latin set, are `Ł` (`U+0141`, `LATIN CAPITAL LETTER L WITH STROKE`) and `Ŧ` (`U+0166`, `LATIN CAPITAL LETTER T WITH STROKE`). Do those fall under the potentially supported category?

**Comment by masaakim** [comment]
@AndydeCleyre Thank you for using!

Absolutely. Attached is a screenshot showing the font editor while the font is being made, and you can see those two glyphs included.

![image](https://github.com/0xType/0xProto/assets/1401513/f3ff0207-9cd4-4a24-8cea-0ac4467bb0d8)

**Comment by masaakim** [comment]
Hey everyone,

Exciting news – I've just rolled out the latest update! Now, 0xProto supports a whopping **344** languages, same as the latest  Intel One Mono version!

Check it out https://github.com/0xType/0xProto/releases/tag/1.600
