### ISSUE TITLE
Texture Healing

### ISSUE THREAD

**Issue by masaakim** [0xType/0xProto#46]
## What

GitHub has released a monospace font named '[monaspace](https://monaspace.githubnext.com/).'
I was impressed by their technique of adjusting the position and size of glyphs while keeping the monospacing intact, referred to as '[Texture Healing](https://github.com/githubnext/monaspace/blob/main/docs/Texture%20Healing.md).' I'm planning to adopt this method for 0xProto as well.

I believe Texture Healing could enhance the legibility of the text.

## How

- Prepare glyphs of different sizes and positions for each character that needs improvement
- Use `calt` feature

**Comment by wass3r** [comment]
will this be optional?

**Comment by masaakim** [comment]
@wass3r Absolutely, same as ligatures.

**Comment by masaakim** [comment]
🚀
