### ISSUE TITLE
Plans to support Cyrillic characters?

### ISSUE THREAD

**Issue by capiet** [0xType/0xProto#48]

**Comment by masaakim** [comment]
After looking into https://github.com/0xType/0xProto/issues/45, I'll decide on the languages to support in 0xProto.

**Comment by masaakim** [comment]
I'm going to close this issue because I don't consider adding Cyrillic characters to be a separate matter.

**Comment by capiet** [comment]
> After looking into #45, I'll decide on the languages to support in 0xProto.

OK, thanks for the reply
