### ISSUE TITLE
Feature request: FP ligatures

### ISSUE THREAD

**Issue by SKyletoft** [0xType/0xProto#5]
Symbols like |>, <|, =<<, >>= etc.

**Comment by masaakim** [comment]
OK, I will include these in next release 👍

**Comment by masaakim** [comment]
@SKyletoft 
https://github.com/0xType/0xProto/pull/7#issuecomment-1646802259
As I stated in this comment, I will be releasing a new version on August 1 with additional FP ligatures.
If you have the time, try the changes in this PR. And feel free to let me know if you have any input.
