### ISSUE TITLE
Fancy Special Characters?

### ISSUE THREAD

**Issue by mrmicahcooper** [0xType/0xProto#50]
Hi,

I love this font and I use it all the time. I recently stumbled across some very fun looking special characters and kindly request (fully acknowledging I have no idea what amount of effort this would take) to also enjoy these in 0xProto.

Ripped from "Maple Mono"

<img width="681" alt="Screenshot 2023-12-15 at 12 17 57 PM" src="https://github.com/0xType/0xProto/assets/698595/0d458576-15bc-4bcf-a624-483be1f7f833">

Is this something you could do in this font, too?

**Comment by masaakim** [comment]
Hi @mrmicahcooper , thanks for using 0xProto!

Creating character variants (`cv` stands for character variant in the context of OpenType) isn't difficult; it mainly involves drawing a Bezier curve in a font editor and adding glyphs. 
However, deciding which variants to create for specific glyphs is a matter of the font's concept.

0xProto is designed for functionality in programming, updated daily for high legibility. Thus, adding glyphs solely for fancy reasons goes against 0xProto's functional concept.
While 0xProto won't support such fancy glyphs, 0xType will keep developing new concept fonts, and I'll consider including variants like those you've suggested in future projects.
