### ISSUE TITLE
semi-bold fonts

### ISSUE THREAD

**Issue by gengchengcai** [0xType/0xProto#51]
Your fonts are great, our entire company of programmers love them, and it would be nice if they were a little thicker.

**Comment by masaakim** [comment]
@gengchengcai Thank you for using!

To address your suggestion about adding more weight to 0xProto, I currently have no plans to do so.
Let me explain the reasons, which are quite detailed.

The main aim of 0xProto is to boost the legibility of source code characters. I believe that legibility depends on two factors.

Firstly, the character's shape should be easily recognizable.
Secondly, the color area of the letters is crucial. In text editors like VS Code or Vim, syntax highlighting aids in color-based character identification, which is more effective with a larger color area or thicker character weight.
However, excessively thick weights can hinder the character's own recognition, especially in a monospace font at small sizes, typical in programming.

Hence, 0xProto's design and its Regular weight, slightly thicker than usual, optimally balance these factors for improved legibility.

**Comment by gengchengcai** [comment]
It's great to hear from you, the word embodiment does have a strong readability as you said, and it's very comfortable to write code. Really thank you for making this font.
