### ISSUE TITLE
Support for variable font

### ISSUE THREAD

**Issue by sonulohani** [0xType/0xProto#53]
Variable fonts are great and better for us to have fonts at any weight. Could you please provide the support for this? Thanks

**Comment by masaakim** [comment]
Hi @sonulohani 

I'm not planning to add weights to 0xProto. You can find the reasons for [this comment](https://github.com/0xType/0xProto/issues/51#issuecomment-1871041738). 

However, I do plan to release some new fonts in 2024, including at least one variable font. It will have a different concept from 0xProto, but I'm sure you'll find it interesting.
