### ISSUE TITLE
[Glyph request] Triple question marks (???)

### ISSUE THREAD

**Issue by pknn** [0xType/0xProto#56]
# Glyph request
## Type
Triple question marks - `???`
## Usage
We use triple question marks `???` in Scala language to indicate thing that has yet to be implemented (often to focus only on the function composition and such)
## How it looks now
![Example](https://github.com/0xType/0xProto/assets/20290728/3f7354a9-7296-499e-958b-f1e9eef0a77a)

**Comment by masaakim** [comment]
@pknn Good catch :+1:

I didn't know Scala had such a syntax. `???` is not an operator, so it should not be ligatured, and when `???` is in a sequence, `??` should be unligatured.
I will fix this in the next patch update!

**Comment by pknn** [comment]
>??? is not an operator, so it should not be ligatured, and when ??? is in a sequence, ?? should be unligatured.

Makes more sense to me. Thank you so much 🙏🏻

**Comment by masaakim** [comment]
Just dropped [v1.601](https://github.com/0xType/0xProto/releases/tag/1.601)! Make sure to update to it.

**Comment by pknn** [comment]
That was fast! Thanks 🙇🏻
