### ISSUE TITLE
Space is narrower on VS Code?

### ISSUE THREAD

**Issue by athos** [0xType/0xProto#59]
Thank you for creating and sharing this font! I love it.

When I set 0xProto as the font on my VS Code, the space character seems to be narrower than other characters. This doesn’t happen with Monaspace or other fonts. In the fourth line of the following screenshots, columns are marked with `^` for every 10 characters (both with ligatures disabled).

- 0xProto
<img width="419" alt="Screenshot 2024-02-13 at 12 09 41" src="https://github.com/0xType/0xProto/assets/27441/3c0546c5-34af-4a95-b5d3-58133257b860">

- Monaspace
<img width="425" alt="Screenshot 2024-02-13 at 12 10 03" src="https://github.com/0xType/0xProto/assets/27441/214bb164-ee29-4102-a70b-f754277a3b16">

This doesn't happen on other applications than VS Code, so it's highly likely just my environment, but do you have any thoughts on what's going on? I'm on 1.601.

**Comment by masaakim** [comment]
@athos Thanks for using 0xProto and for your detailed feedback!
I managed to replicate the issue on my end and I'm diving into figuring out what's causing it right away.

<img width="752" alt="image" src="https://github.com/0xType/0xProto/assets/1401513/fec52a65-9192-44ba-866b-59c1d7654cf7">

**Comment by masaakim** [comment]
Sorted it out and just rolled out version [1.602](https://github.com/0xType/0xProto/releases/tag/1.602).
Given it's a monospace programming font, this bug was pretty major. Really appreciate your report!

**Comment by athos** [comment]
Thanks for the quick fix! Tried 1.602 and confirmed that all columns are now perfectly aligned!
