### ISSUE TITLE
Suggestion: add Unicode spaces

### ISSUE THREAD

**Issue by MIvanchev** [0xType/0xProto#61]
First I want to say a big THANK YOU for this really impressive font that I now use for my mode line :) I would like to suggest the addition of the Unicode spaces, especially the ones after 0x2000. You can see a list [here](U+2000).

**Comment by masaakim** [comment]
Thank you too for using 0xProto and for your suggestion. 
Embarrassingly, I just realized there are tons of different whitespace characters in Unicode. Give me a sec to wrap my head around them before I support it.

**Comment by MIvanchev** [comment]
There are plenty, it's true :smile:

**Comment by masaakim** [comment]
Right now, 0xProto includes the uni0020 and uni00A0 Unicode spaces.

Other programming fonts have supported these additional Unicode spaces:

### JetBrains Mono

- uni0020
- uni00A0
- uni000D
- uniFEFF

### Fira Code

- uni0020
- uni00A0
- uni2007
- uni2008
- uni200B
- uni000D
- uniFEFF

### Victor Mono

- uni0020
- uni00A0
- uni000D

### MonoLisa

- uni0020
- uni00A0

same as 0xProto

### Intel One Mono

- uni0020
- uni00A0

same as 0xProto

### Monaspace 

- uni0020
- uni00A0

same as 0xProto

**Comment by masaakim** [comment]
In https://github.com/0xType/0xProto/issues/61#issuecomment-1987810669 , I compared 0xProto with other popular open-source programming fonts.
Found out Fira Code has the most Unicode spaces. Made me think it's a good move to include the same ones in 0xProto.
So, I've decided to add these five glyphs this time:

- uni2007
- uni2008
- uni200B
- uni000D
- uniFEFF

@MIvanchev Can I get your opinion on this?

**Comment by MIvanchev** [comment]
IMHO 0x000D doesn't make much sense as it's a control char. The others are IMO It's a good idea, I use more than that set personally to format stuff but it definitely makes sense to include those. The period space is very important for me :+1:

**Comment by masaakim** [comment]
Thank you! I just want to ask a question to make 0xProto better, not just do the same thing as other fonts.

> I use more than that set personally to format stuff

In what situations, aside from this one, would you use other Unicode spaces? Is it mainly in programming?

**Comment by MIvanchev** [comment]
No, I use 0xProto (or intend to use it) for the mode line of my WM. I like it because it's thicker but not as thick as bold face and extremely legible. I use the Unicode spaces to fine tune, i.e. to fit more on a laptop display. Of course, no need to provide the glyphs if the font is monospaced (I just figured this out today).

**Comment by masaakim** [comment]
Thanks, I understand.

By the way, this hasn't been officially announced yet, but I'm planning to release a proportional font next month for typing natural language, not programming, that will inherit features from 0xProto. This new font might be better suited to your needs ;)

**Comment by masaakim** [comment]
Hi @MIvanchev

I've just released [v1.603](https://github.com/0xType/0xProto/releases/tag/1.603) to support more Unicode spaces 👍

**Comment by MIvanchev** [comment]
I read you, but doesn't that go against the monospaced nature of 0xProto? Btw, I've kept 0xProto for my mode line, thanks for this epic font.
