### ISSUE TITLE
Font renders poorly in Intellij IDE's on Windows

### ISSUE THREAD

**Issue by hesselmonk** [0xType/0xProto#67]
I _think_ it might be hinting related, the descender of the f and the bottom of the c look off to me in this example:

![image](https://github.com/0xType/0xProto/assets/28805623/b3eb905d-fbe6-4209-97d4-91fa354a6867)

On macOS it looks like this:

<img width="297" alt="image" src="https://github.com/0xType/0xProto/assets/28805623/00b5fa52-4073-42e4-88aa-a41db9198e33">

Windows, Version 1.603

**Comment by masaakim** [comment]
@hesselmonk Thanks for the feedback!

I would like to know more information:

- What is the resolution (dpi) of your display?
- What px font size are you using?

**Comment by hesselmonk** [comment]
Hey sure, font size: 13.0 (no clue what units Intelij IDE's use), resolution: 1920 x 1080 (96dpi)

I've installed the .ttf version, looking at it in the Windows font settings it seems to be missing a bit of meta info.

![image](https://github.com/0xType/0xProto/assets/28805623/e46bb204-12c8-4986-899c-3596a4d8e4f9)

**Comment by masaakim** [comment]
Could you try with this font file? (It includes changes in https://github.com/0xType/0xProto/issues/68 ) I've set auto hinting using [ttfautohint-py](https://github.com/fonttools/ttfautohint-py) when the font was built.

[0xProto-Regular-fixed_monospace-and-auto_hinting.zip](https://github.com/0xType/0xProto/files/15032434/0xProto-Regular-fixed_monospace-and-auto_hinting.zip)

**Comment by hesselmonk** [comment]
Yes, it renders _much nicer_ now.

![image](https://github.com/0xType/0xProto/assets/28805623/91fd0554-b289-4edb-8a64-bf1bfdb58fe6)

I do have to point out that Intellij IDE's have always had a funky way of rendering text. For reference this is what the same text, same size, looks like on this machine in VSCode:

![image](https://github.com/0xType/0xProto/assets/28805623/91ac69a7-3b13-47c4-aae5-1e2750d55fba)
