### ISSUE TITLE
Stylistic Set for non-cursive variants

### ISSUE THREAD

**Issue by matype** [0xType/0xProto#71]
## What

TSIA

## Ref

https://github.com/0xType/0xProto/issues/20#issuecomment-2075678060

**Comment by matype** [comment]
Hi @my4ng , I've just released [v2.100](https://github.com/0xType/0xProto/releases/tag/2.100) to add non-script italic variant.

By default, just italics added this time are used, and if `ss01` is specified, it is scripted.

Try it out if you like :)

**Comment by my4ng** [comment]
@matype Thank you! Just tested it out and it's awesome! :tada: 

Just for other's reference: `"editor.fontLigatures": "'ss01'"` will turn on the cursive feature in VS Code.

**Comment by matype** [comment]
Yes, just updated the README 😉  https://github.com/0xType/0xProto/commit/957808a8f2e4eb641a251de56b6dd27372969518
