### ISSUE TITLE
Multiple `|` become ligatures

### ISSUE THREAD

**Issue by my4ng** [0xType/0xProto#73]
`|` groups are bunched into pairs in TUI applications:

![image](https://github.com/0xType/0xProto/assets/17978089/0b832a49-6ff6-4ae4-94e0-b9dfdaf7976d)

I guess a possible fix would be "if there are three or more `|` next to each other, then don't put them into ligature."

**Comment by masaakim** [comment]
@my4ng Thanks for the feedback. I will fix it in the next release.

**Comment by masaakim** [comment]
Just dropped [v2.001](https://github.com/0xType/0xProto/releases/tag/2.001)! Make sure to update to it.

**Comment by my4ng** [comment]
@masaakim Thank you for the fix! Tested and works like a charm!
![image](https://github.com/0xType/0xProto/assets/17978089/3968c09d-c1fb-43ac-afe3-99ad6a241ba3)
