### ISSUE TITLE
Some letters appear as cut-outs in kitty

### ISSUE THREAD

**Issue by pithecantrope** [0xType/0xProto#76]
'm' almost looks like 'n' in neovim:
![Screenshot from 2024-06-24 22-28-25](https://github.com/0xType/0xProto/assets/69684823/313e04a7-3968-410f-9621-51475b6a3313)

Terminal - kitty:
![Screenshot from 2024-06-24 22-36-55](https://github.com/0xType/0xProto/assets/69684823/126c6e7c-f13a-4871-904a-aca800e365bd)

modify_font  cell_width 110% doesn't really helping:
![Screenshot from 2024-06-24 22-43-36](https://github.com/0xType/0xProto/assets/69684823/8fc0a80f-9bb7-4345-914b-42da072212df)

Weird thing is, if I:
![Screenshot from 2024-06-24 22-46-48](https://github.com/0xType/0xProto/assets/69684823/3befa577-491a-4672-9c8e-5c057dc4f6c8)
'm' is still fucked up

Btw, my theme is - [https://github.com/dasupradyumna/midnight.nvim](url)

BUT if I set my theme to default, like, retrobox, then it fixes it!
![Screenshot from 2024-06-24 22-49-06](https://github.com/0xType/0xProto/assets/69684823/97adbb25-f1c6-4dc0-945c-d83d61eaa8a7)

What is happening? Is it problem with your amazing font, kitty or my theme?

**Comment by pithecantrope** [comment]
It's really a Kitty-rendering issue:
![Screenshot from 2024-07-06 11-55-20](https://github.com/0xType/0xProto/assets/69684823/86bf0d18-1394-4176-8a75-4e1245c4c0ed)

**Comment by matype** [comment]
I see. At least it doesn't seem to be an issue with the nvim theme. Does the same problem occur when rendering with other fonts in Kitty?

**Comment by pithecantrope** [comment]
Yes, the same problem with Iosevka (M is cut-out): 
![Screenshot from 2024-07-06 12-35-20](https://github.com/0xType/0xProto/assets/69684823/858f6351-cb06-4a35-81d0-19b7de5498a3)

I think this will fix it, right?
https://github.com/kovidgoyal/kitty/issues/7570#issue-2369183273

**Comment by matype** [comment]
Thank you for verifying! 
This is not related to the font but is a problem with kitty. This issue is closed.

**Comment by pithecantrope** [comment]
> Your font needs to have an italic face that is metric compatible with the regular face for that, it has no connection with font selection/features/variability. - kovidgoyal (kitty creator)

Can't stand the cut offs so I guess I have to go back to the jetbrains Mono until something changes :(

**Comment by matype** [comment]
0xProto and 0xProto Italic are exactly the same metric 🤔 
And probably almost all other monospaced fonts do too.
