### ISSUE TITLE
Add bold weight

### ISSUE THREAD

**Issue by matype** [0xType/0xProto#79]
## What

Try to make bold weight experimentally.

ref: https://github.com/0xType/0xProto/issues/8#issuecomment-2252180239

**Comment by mcchrish** [comment]
Thank for considering! And I really like this font so far. It's the only font that got me out of Iosevka.

**Comment by matype** [comment]
I've finished making the Roman (non-italicised) Bold all the way through!

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/d0084a45-a44a-42b0-8a52-56a0ee72c624">

And this is a display confirmation in VS Code. `if` and `function`, etc. are Bold.

<img width="1822" alt="image" src="https://github.com/user-attachments/assets/b63ea233-f736-49a6-8167-67eca71ce0e9">

The current 0xProto Bold .otf file is attached for you to try if you are interested.

[0xProto-Bold-beta-1.otf.zip](https://github.com/user-attachments/files/16581012/0xProto-Bold-beta-1.otf.zip)

**Comment by matype** [comment]
By the way, I will not be making a Bold Italic for 0xProto.

Because 0xProto is a programming font, and while Bold or Italic is necessary as a means of highlighting other than by color, wouldn't a Bold and Italic family be fine without it?

I know that it is not a problem to have. But I have a lot of other projects I want to do besides 0xProto, and I don't want to add as many things as possible that I need to keep maintaining.

**Comment by jastko** [comment]
Under Linux, in Konsole - KDE's Terminal Emulator, Bold weight has different line spacing than Regular.

https://github.com/user-attachments/assets/9472dacb-1761-4514-a1f4-6e520f74855b

FontForge shows different metrics for Regular(left)/Bold(right) wieghts.
![protoboldfont_20240813_080930](https://github.com/user-attachments/assets/7487e12a-a137-4b16-9fb8-38c5e82df914)

Font version: 2.100 Regular/Beta-1 for Bold

**Comment by matype** [comment]
@jastko Thanks for the feedback! 

I've fixed it and you can check it with the font file here. [0xProto-Bold-beta-2.zip](https://github.com/user-attachments/files/16599028/0xProto-Bold-beta-2.zip)

<img width="1449" alt="image" src="https://github.com/user-attachments/assets/294ba2e6-3e53-417b-a2ea-55bad5ddbae0">

I also checked this .otf in the tool I use and the metrics in the OS/2 Table are the same.

**Comment by jastko** [comment]
**Line spacing has been fixed**, but now Konsole doesn't distinguish between Regular and Bold weight. 

https://github.com/user-attachments/assets/94df85d6-64dd-4c2b-9659-eb77a936e187

It's probably caused, by incorrectly set weight. FontForge shows, that WeihgtClass is set to 400. 
![protoboldfont_weightclass_20240813_175203](https://github.com/user-attachments/assets/8fab582e-5037-4412-b4b7-a2bfc04aad54)

In previous version(Beta-1), WeightClass was set to 700.

**Comment by distefam** [comment]
This is great, thank you! I've been experimenting with using a colorscheme called [Zenbones](https://github.com/zenbones-theme/zenbones.nvim) that relies on font styles more than colors.

**Comment by matype** [comment]
@distefam Thank you for the feedback.

> I can confirm that the new beta 2 version doesn't distinguish between regular and bold weights correctly.

Probably for the same reason as https://github.com/0xType/0xProto/issues/79#issuecomment-2286635928

**Comment by matype** [comment]
Fixed in beta-3! I think this will work well now. (I won't post a screenshot, but I have checked the OS/2 table for the generated font files.)

[0xProto-Bold-beta-3.zip](https://github.com/user-attachments/files/16604029/0xProto-Bold-beta-3.zip)

**Comment by distefam** [comment]
I just tried beta 3, and I can say that the bold and regular fonts both render correctly and have proper baseline alignment. Thank you!

**Comment by distefam** [comment]
Actually, I may have spoken too soon. It appears that now the Italic variant, which I had retained from the last release, displays with a different baseline:
![image](https://github.com/user-attachments/assets/8f3110ba-2ddf-44e7-8f1d-efece1d0cd10)

**Comment by jastko** [comment]
I can confirm. Regular/Bold(ttf/otf) font metrics have changed back to those from Beta 1. VendorID has also changed, so there are now two instances of 0xProto. Beta3 fonts have VendorID set to UKWN.

Picture below.

![proto_beta3_vendorid_20240813_214214](https://github.com/user-attachments/assets/0e8fcddb-2515-4b3f-ac2e-ff69c55027f2)

**Comment by matype** [comment]
Great.

> here are now two instances of 0xProto. Beta3 fonts have VendorID set to UKWN.

I was concerned that the achVendID in the OS/2 table was "0xTy" instead of 0xType, so I checked and found that it was [the Vendor ID registered with Microsoft](https://learn.microsoft.com/en-us/typography/vendors/register) and not 0xType, which I intentionally removed in Beta 3.

**Comment by arjpar** [comment]
> wouldn't a Bold and Italic family be fine without it?

@matype While Bold Italic is rare, I think it would be good to have it as the default styles/weights operations you can do is Bold, Italicize, and the combination of the 2 (Bold Italic). Some themes probably use Bold Italic, but it's rare I think. I still think it would be good to have Bold Italic as it would make 0xProto feature complete in that sense, but it doesn't have to be immediate.

**Comment by matype** [comment]
Finally released! https://github.com/0xType/0xProto/releases/tag/2.200

@arjpar If I ever create a Bold Italic family, I'll create another issue at that time.
