### ISSUE TITLE
Nerd font

### ISSUE THREAD

**Issue by aehabdelouadoud** [0xType/0xProto#82]
Firstly, thanks for this beautiful font :)
I think it's going to be a good idea if there's a fork for nerd stuff for this font that includes support for bold and italic too, and thanks :)

**Comment by matype** [comment]
Great, but I wasn't sure what you were trying to solve with this issue.
If you want to use 0xProto from Nerd font, the [v1.602](https://github.com/ryanoasis/nerd-fonts/pull/1516) has already been merge and there was a [PR to support the latest v2.100](https://github.com/ryanoasis/nerd-fonts/pull/1623). Thanks to @my4ng :)

**Comment by Finii** [comment]
New Nerd Font release with 0xProto 2.2 is expected next week or week thereafter.

What 0xProto is missing is a **_bold and italic_** variant, to complete the RIBBI set :slightly_smiling_face:
Maybe the TO meant that?
Shell-prompts often use both together.

![image](https://github.com/user-attachments/assets/5d746c05-2557-42da-bad5-27116856936e)

_No `0xProto-BoldItalic.ttf`_

**Comment by Finii** [comment]
@horanmustaplot 

![image](https://github.com/user-attachments/assets/304f06fa-3bfc-49ea-8b37-93383d3785ab)

Not?

**Comment by horanmustaplot** [comment]
> @horanmustaplot
> 
> ![image](https://private-user-images.githubusercontent.com/16012374/363646652-304f06fa-3bfc-49ea-8b37-93383d3785ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNzMwNjIsIm5iZiI6MTcyNTI3Mjc2MiwicGF0aCI6Ii8xNjAxMjM3NC8zNjM2NDY2NTItMzA0ZjA2ZmEtM2JmYy00OWVhLThiMzctOTMzODNkMzc4NWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDEwMjYwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNmNiNzFjYmUxZDc2NmNmNGE3YTgyNmYzMjg5ODJiMTY2MzZlOGRiZmI3Y2E5MDg4ZGRmNGI4NDNjYjcyOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H7Jyb7UJu3Gmh5Tbae1BuW1Gklp_v05pi7hwTsEwwpM)
> 
> Not?

I mean it's a great news, thx by the way

**Comment by matype** [comment]
@matype Thank you for your information.

> New Nerd Font release with 0xProto 2.2 is expected next week or week thereafter.

Great news!

> What 0xProto is missing is a bold and italic variant, to complete the RIBBI set 🙂

This is why I did not make Bold Italic at the same time as Bold: https://github.com/0xType/0xProto/issues/79#issuecomment-2283765005
I don't know much about font conventions, but to what extent is the RIBBI set a rule that needs to be followed?

> Maybe the TO meant that?

I'm sorry, what does this one mean...?

**Comment by Finii** [comment]
> to what extent is the RIBBI set a rule that needs to be followed?

To no extend at all ;-)
It's just that most fonts that come in not-only-regular come at least as set of **R**egular **I**talic **B**old **B**old**I**talic.

Terminal emulators often can set these 4 fonts.
If you buy fonts you can usually buy a Ribbi set at a discount (as that is mostly used).

If 0xProto has a BoldItalic or not is completely your decision.

> > Maybe the TO meant that?
> 
> I'm sorry, what does this one mean...?

"Maybe horanmustaplot meant that" (TO = thread .... originator ;-) my bad :roll_eyes: )

**Comment by matype** [comment]
https://github.com/ryanoasis/nerd-fonts/pull/1623 has been merged, so I'll close this issue. Thank you for Nerd Fonts!
