### ISSUE TITLE
Dash height isn't consistent with arrow ligature (some sizes only)

### ISSUE THREAD

**Issue by ckafi** [0xType/0xProto#86]
Firstly, let me thank you for this amazing font. It's the first coding font for which I don't disable ligatures, because I like to see the individual glyphs.

Now for my issue:

The vertical height of the dash `-` is inconsistent with the `->` ligature, meaning it's either too low or too high for some font sizes (most seem to be fine). Here are examples from KDE Konsole in font sizes 11 and 19:

![Screenshot_20240904_142733](https://github.com/user-attachments/assets/99abc404-35a6-4275-8eaa-7e87810b22c8) ![Screenshot_20240904_142947](https://github.com/user-attachments/assets/c0e499bb-50a9-4da5-9fbd-27c4a384bac4)

Same issue happens in Kitty and VS Code, just for different font size values.

It could be a hinting issue with my setup, but I don't think it is. This is with hinting turned off:

![Screenshot_20240904_144507](https://github.com/user-attachments/assets/f524b1b9-206e-441f-a7ac-a121c95b2f6a)

**Comment by ckafi** [comment]
Never mind, it seems it is my setup. When i set my display to a different scaling factor the issue goes away.

**Comment by matype** [comment]
OK, Thank you for using 0xProto!
