### ISSUE TITLE
Please add Cyrillic symbols

### ISSUE THREAD

**Issue by vladon** [0xType/0xProto#89]
Please add Cyrillic symbols for Russian, Ukrainian, Serbian, etc.

**Comment by matype** [comment]
@vladon Thank you for using but 0xProto supports only Latin characters. See also https://github.com/0xType/0xProto/issues/45#issuecomment-1849383460 and https://github.com/0xType/0xProto/issues/48

**Comment by MIvanchev** [comment]
I just want to chime in and say that I use 0xProto for a long time now and it's the best font I've used but Cyrillic support would really make it STELLAR.

**Comment by matype** [comment]
@MIvanchev Thank you for using 0xProto and I'm so glad to hear that!
But my opinion has not changed since I posted [this comment](https://github.com/0xType/0xProto/issues/89#issuecomment-2371143187)...

**Comment by MIvanchev** [comment]
No problem @matype, just expressing fond feelings! Regarding the Cyrillic chars, there's definitely need but we understand how open source works :) Keep it rocking!
