### ISSUE TITLE
More exaggerated curly braces?

### ISSUE THREAD

**Issue by forrcaho** [0xType/0xProto#90]
As an aging developer, I'm having more and more trouble distinguishing between parentheses and curly braces at the ~12pt text size I like to use.

The curly braces in 0xProto are actually quite good when compared with other programming fonts, but I wonder if they could be made more exaggerated -- even to the point where they look silly -- to make them clearly distinguishable from parentheses even at small text sizes.

I wish I was better at some drawing tool so I could draw what I'm thinking of: the best I can describe it, taking the entire width of the monospace character, make something like an "S" in the top half, with its mirror image below. Each top and bottom would have a curve that takes up the entire font width.

If the drawing tool you used to create this font is freely available, I could try to design the curly braces I'd like.

**Comment by matype** [comment]
@forrcaho Thank you for using my font!

Typeface design is not something that can be judged by looking at just one character and deciding that it would be better (more readable) if it were shaped like that. And 0xProto is designed to make it much easier to identify individual characters.

My intuition from experience is that applying the design you suggested would result in poor balance throughout the text 🤔 

I use the paid font editor [Glyphs](https://glyphsapp.com/) or [RoboFont](https://robofont.com/), but there are also some free tools, so if you like, please feel free to fork and edit them! (While generative AI is at its height, it's good to calm down by editing Bezier curves by hand 🙂 )

**Comment by cormullion** [comment]
You might find [this issue](https://github.com/intel/intel-one-mono/issues/29) interesting.

**Comment by matype** [comment]
Thanks, I read the issue with great interest 👍 

On that basis, I would like to convey the following:
- 0xProto is not like Intel One Mono, but it already has a design that emphasizes curly brackets quite a bit
- It's nice to get feedback, but just because there's a lot of feedback doesn't mean it's a reason to change
- I'm not in the same position as Intel :)

**Comment by matype** [comment]
My opinion has not changed since this comment https://github.com/0xType/0xProto/issues/90#issuecomment-2398554966 , and this is no longer an issue for now, so I'll close it.
