### ISSUE TITLE
A thinner version would be awesome.

### ISSUE THREAD

**Issue by fazleyrabby** [0xType/0xProto#91]
I have used this font for a while, Is it possible to get a thinner version of this font?

**Comment by matype** [comment]
@fazleyrabby Thank you for using!

In 0xProto, the Regular weight is a tad thicker compared to similar weights in other programming fonts. This subtle change allows for more generous syntax highlighting, making character identification a breeze.
There is a possibility that I will add a thinner weight in the future, but it will be a low priority.

**Comment by matype** [comment]
If I add a thinner family, I will create a new issue, so I will close this issue
