### ISSUE TITLE
Cannot set font in VSCode

### ISSUE THREAD

**Issue by NoahELE** [0xType/0xProto#92]
I installed the otf version of this font, but I cannot set it in VSCode.

**Comment by my4ng** [comment]
It works in VS Code for me. Have you tried specify it in the settings JSON directly:

```
"editor.fontFamily": "0xProto Nerd Font",
```

If that still doesn't work, perhaps try the ttf version.

**Comment by NoahELE** [comment]
No, the ttf version did not work either. Did you use the Nerd Font version?

```
"editor.fontFamily": "0xProto, Cascadia Code NF",
```

My setting is like this.

**Comment by my4ng** [comment]
I use the nerd font version, which should hopefully update to the newest version soon. Try enclosing 0xProto in quotes:

```
"editor.fontFamily": "'0xProto', Cascadia Code NF",
```

**Comment by NoahELE** [comment]
Thanks, it worked!

I didn't know I need to use single quotes to enclose the font before.

**Comment by matype** [comment]
Great 👍 
See also: https://github.com/0xType/0xProto?tab=readme-ov-file#visual-studio-code
