### ISSUE TITLE
Additional font weight variants

### ISSUE THREAD

**Issue by rasmus-kristensen** [0xType/0xProto#94]
Hello,

would it be possible to make the font available in more font weight variants?
Personally I would love a semi-bold/medium variant also. 

Thank you for this awesome font!

**Comment by matype** [comment]
Hi @rasmus-kristensen , Thank you for using 0xProto!

> would it be possible to make the font available in more font weight variants?
Personally I would love a semi-bold/medium variant also

At the moment, there are no plans to add any other family other than [Bold Italic](https://github.com/0xType/0xProto/issues/85), which is currently an open issue
There have been similar issues in the past, so please check the details below

- https://github.com/0xType/0xProto/issues/8
- https://github.com/0xType/0xProto/issues/53
- https://github.com/0xType/0xProto/issues/79
