### ISSUE TITLE
Delete  __MACOSX folder from release packages

### ISSUE THREAD

**Issue by hongquan** [0xType/0xProto#95]
Please delete  __MACOSX folder from .zip.

**Comment by matype** [comment]
@hongquan Thanks, I've just deleted it from [the latest version](https://github.com/0xType/0xProto/releases/tag/2.201)

**Comment by mrfragger** [comment]
`zip -r dir.zip . -x "*.DS_Store"`

Navigate to the directory you wish to zip on mac and this avoids putting .DS_Store and __MACOSX folders which are annonying for Linux and Windows users.
